spring.application.name=ecotrack

server.port=8081

# ?????????????????????????????????????????
# MYSQL DATABASE CONFIG
# ?????????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/ecotrackdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?????????????????????????????????????????
# JPA / HIBERNATE CONFIG
# ?????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ?????????????????????????????????????????
# SWAGGER CONFIG
# ?????????????????????????????????????????
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.mapper.accept-case-insensitive-enums=true

#{
#"industryId": 4,
#"type": "CO2",
#"quantity": "25.50",
#"date": "2026-03-17",
#"status": "PENDING"
#
#}